version: '3'
services:
  graphql-server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "4001:4001"
    volumes:
      - /app/node_modules
      - ./server:/app
  react-client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app