version: '3'
services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "3050:80"
    depends_on:
      - graphql-server
      - react-client
  graphql-server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./server:/app
  react-client:
    environment:
      - WDS_SOCKET_PORT=0
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
  react-client-tests:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "test"]
    
